services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crud_basico
    volumes:
      - postgres-doc:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: pedrozonta21/api-crud-simples
    build: 
      context: .
    ports: 
     - 5000:80
    depends_on:
      - db

volumes:
  postgres-doc: