services:
  db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: crud_basico
    volumes:
      - postgres-doc:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  db-mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_basico
      MYSQL_USER: pedro
      MYSQL_PASSWORD: pedro
    volumes:
      - mysql-doc:/var/lib/mysql
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
     
  app:
    image: api
    build: 
      context: .
    ports: 
      - 5000:80
    depends_on:
      - db-postgres
      - db-mysql

volumes:
  postgres-doc:
  mysql-doc: